class PracticePageElements:

    suggestion_class_xpath = "/html/body/div[1]/div[2]/fieldset/input"
    mexico_country_xpath = "/html/body/ul/li[6]/div"
    dropdown_example_xpath = "//*[@id='dropdown-class-example']"
    dropdown_example_id = "dropdown-class-example"
    dropdown_option2_xpath = "//*[@id='dropdown-class-example']/option[3]"
    dropdown_option3_xpath = "//*[@id='dropdown-class-example']/option[4]"
    switch_window_button_xpath = "/html/body/div[2]/div[1]/fieldset/button"
    switch_alert_field_xpath = "/html/body/div[2]/div[3]/fieldset/input[1]"
    switch_alert_btn_xpath = "/html/body/div[2]/div[3]/fieldset/input[2]"
    confirm_alert_btn_css = "#confirmbtn"
    table_xpath = "/html/body/div[3]/div[1]/fieldset/table/tbody"
    table_row_xpath = "//table[@class='table-display']/tbody/tr"
    table_name_column_xpath = "//table[@class='table-display']/tbody/tr/td[2]"
    table_price_column_xpath = "//table[@class='table-display']/tbody/tr/td[3]"
    table_fixed_header_xpath = "/html/body/div[3]/div[2]/fieldset[2]/div[1]"
    table_fixed_header_row_xpath = "//div[@class='tableFixHead']/table[@id='product']/tbody/tr"
    table_fixed_header_names_xpath = "//div[@class='tableFixHead']/table[@id='product']/tbody/tr/td[1]"
    table_fixed_header_position_xpath = "//div[@class='tableFixHead']/table[@id='product']/tbody/tr/td[2]"
    iframe_example_id = "courses-iframe"
    iframe_text_mentorship_xpath = "/html/body/div/div[2]/section[2]/div/div/div/div[2]/ul/li[2]"
    iframe_list_xpath = "/html/body/div/div[2]/section[2]/div/div/div/div[2]"
